# filename: agents/qualitative.py — Code Generated by Sidekick is for learning and experimentation purposes only.
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
import os
import chromadb
from openai import OpenAI

load_dotenv()

client = OpenAI(
    api_key=os.getenv("GEMINI_API_KEY"),
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
)

# Replace this with the exact model used during document ingestion.
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")


def retrieve(query: str, top_k: int = 5) -> list[dict]:
    chroma = chromadb.PersistentClient(path="./data/chroma")
    collection = chroma.get_collection("enterprise-docs")

    embedding = embedding_model.encode([query]).tolist()
    results = collection.query(
        query_embeddings=embedding,
        n_results=top_k,
    )

    return [
        {
            "content": document,
            "source": metadata["source"],
            "chunk": metadata["chunk"],
        }
        for document, metadata in zip(
            results["documents"][0],
            results["metadatas"][0],
        )
    ]


def build_prompt(query: str, chunks: list[dict]) -> str:
    context = ""

    for i, chunk in enumerate(chunks):
        context += (
            f"[Source {i + 1}: {chunk['source']}]\n"
            f"{chunk['content']}\n\n"
        )

    return f"""You are a helpful enterprise documentation assistant.

Answer the question using ONLY the context provided below.

If the answer is not in the context, say:
"I cannot find this information in the provided documents."

Always cite the source number(s) you used.

CONTEXT:
{context}

QUESTION: {query}

ANSWER:"""


def run(query: str) -> dict:
    chunks = retrieve(query)
    prompt = build_prompt(query, chunks)

    response = client.chat.completions.create(
        model="gemini-3.5-flash-lite",
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )

    usage = response.usage

    return {
        "answer": response.choices[0].message.content or "",
        "chunks": chunks,
        "input_tokens": usage.prompt_tokens if usage else 0,
        "output_tokens": usage.completion_tokens if usage else 0,
    }
